"""Create form_data table

Revision ID: 3dfba3d858ce
Revises: a5608d2de0b2
Create Date: 2024-07-14 19:37:30.652267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dfba3d858ce'
down_revision = 'a5608d2de0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snot22', sa.Integer(), nullable=True),
    sa.Column('vas', sa.Integer(), nullable=True),
    sa.Column('olfactory_test', sa.Integer(), nullable=True),
    sa.Column('previous_surgeries', sa.Integer(), nullable=True),
    sa.Column('corticosteroid_use', sa.Integer(), nullable=True),
    sa.Column('polyp_size', sa.Integer(), nullable=True),
    sa.Column('sinus_opacification', sa.Integer(), nullable=True),
    sa.Column('asthma', sa.Integer(), nullable=True),
    sa.Column('nsaid_intolerance', sa.Integer(), nullable=True),
    sa.Column('serum_eosinophilia', sa.Integer(), nullable=True),
    sa.Column('tissue_eosinophilia', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('submission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snot22', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('olfactory_test', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_surgeries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('corticosteroid_use', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('polyp_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sinus_opacification', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asthma', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nsaid_intolerance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('serum_eosinophilia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tissue_eosinophilia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='submission_pkey')
    )
    op.drop_table('form_data')
    # ### end Alembic commands ###
