"""Initial migration

Revision ID: a5608d2de0b2
Revises: 
Create Date: 2024-07-14 18:07:04.719141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5608d2de0b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snot22', sa.Integer(), nullable=True),
    sa.Column('vas', sa.Integer(), nullable=True),
    sa.Column('olfactory_test', sa.Integer(), nullable=True),
    sa.Column('previous_surgeries', sa.Integer(), nullable=True),
    sa.Column('corticosteroid_use', sa.Integer(), nullable=True),
    sa.Column('polyp_size', sa.Integer(), nullable=True),
    sa.Column('sinus_opacification', sa.Integer(), nullable=True),
    sa.Column('asthma', sa.Integer(), nullable=True),
    sa.Column('nsaid_intolerance', sa.Integer(), nullable=True),
    sa.Column('serum_eosinophilia', sa.Integer(), nullable=True),
    sa.Column('tissue_eosinophilia', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    # ### end Alembic commands ###
